micronaut:
  application:
    name: demo
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: ''
    schema-generate: CREATE_DROP
    dialect: POSTGRES
cassandra:
  default:
    clusterName: '"myCluster"'
    contactPoint: '"localhost"'
    port: 9042
    maxSchemaAgreementWaitSeconds: 20
    ssl: true
jpa.default.properties.hibernate.hbm2ddl.auto: update
nats.addresses:
- nats://localhost:4222
redis.uri: redis://localhost
